---
kind: pipeline
type: docker
name: scan

concurrency:
  limit: 1

steps:

  - name: host keyscan
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
    settings:
      requirements: .ansible/files/requirements.txt
      inventory: .ansible/inventories/proxmox.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/scan_hosts.yaml
      vault_password:
        from_secret: ansible_vault_password 
      private_key:
        from_secret: automation_id_rsa

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: bootstrap

concurrency:
  limit: 1

steps:

  - name: bootstrap machines
    image: docker.nexus.diesel.net/drone-ansible:7.2.0
    environment:
      CLOUD_INIT_USER:
        from_secret: cloud_init_user
      CLOUD_INIT_PASS:
        from_secret: cloud_init_pass
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      requirements: .ansible/files/requirements.txt
      inventory: .ansible/inventories/proxmox.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/bootstrap.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password 

trigger:
  branch:
    - stable
  event:
    - push
...
