---
kind: pipeline
type: docker
name: scan

concurrency:
  limit: 1

steps:

  - name: host keyscan
    image: docker.nexus.diesel.net/drone-ansible:5.3.0
    environment:
    settings:
      requirements: .ansible/files/requirements.txt
      inventory: .ansible/inventories/fleet.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/scan_hosts.yaml
      vault_password:
        from_secret: ansible_vault_password 

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: bootstrap

concurrency:
  limit: 1

steps:

  - name: bootstrap machines
    image: docker.nexus.diesel.net/drone-ansible:5.3.0
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      CLOUD_INIT_USER:
        from_secret: cloud_init_user
      CLOUD_INIT_PASS:
        from_secret: cloud_init_pass
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      requirements: .ansible/files/requirements.txt
      inventory: .ansible/inventories/fleet.yaml
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/bootstrap.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password 

trigger:
  branch:
    - stable
  event:
    - push

---

kind: pipeline
type: docker
name: daily maintenance

concurrency:
  limit: 1

steps:
  - name: update packages
    image: docker.nexus.diesel.net/drone-ansible:5.3.0
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      requirements: .ansible/files/requirements.txt
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/update.yaml
      inventory: .ansible/inventories/fleet.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - cron
  cron:
    - daily_maintenance

---

kind: pipeline
type: docker
name: weekly maintenance

concurrency:
  limit: 1

steps:
  - name: clean docker artifacts
    image: docker.nexus.diesel.net/drone-ansible:5.3.0
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      requirements: .ansible/files/requirements.txt
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/clean.yaml
      inventory: .ansible/inventories/fleet.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password


trigger:
  event:
    - cron
  cron:
    - weekly_maintenance
