---
kind: pipeline
type: docker
name: development pipeline

clone:
  depth: 1

steps:
  - name: configure ssh
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      SUPER_USER:
        from_secret: super_user
      SUPER_PASS:
        from_secret: super_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/configure_ssh.yaml
      inventory: .ansible/inventory/development/hosts
      vault_password:
        from_secret: ansible_vault_password 

  - name: deploy
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventory/development/hosts
      vault_password:
        from_secret: ansible_vault_password 

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: test pipeline

clone:
  depth: 1

steps:
  - name: configure ssh
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      SUPER_USER:
        from_secret: super_user
      SUPER_PASS:
        from_secret: super_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/configure_ssh.yaml
      inventory: .ansible/inventory/stable/hosts
      vault_password:
        from_secret: ansible_vault_password 

  - name: deploy
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventory/stable/hosts
      vault_password:
        from_secret: ansible_vault_password 


trigger:
  branch:
    - stable
  event:
    - push

---
kind: pipeline
type: docker
name: production pipeline

clone:
  depth: 1

steps:
  - name: configure ssh
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      SUPER_USER:
        from_secret: super_user
      SUPER_PASS:
        from_secret: super_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/configure_ssh.yaml
      inventory: .ansible/inventory/production/hosts
      vault_password:
        from_secret: ansible_vault_password 

  - name: deploy
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventory/production/hosts
      vault_password:
        from_secret: ansible_vault_password 


trigger:
  event:
    - tag
...
