---
kind: pipeline
type: docker
name: swarm bootstrap

steps:

  - name: bootstrap
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      CLOUD_INIT_USER:
        from_secret: cloud_init_user
      CLOUD_INIT_PASS:
        from_secret: cloud_init_pass
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      requirements: .ansible/files/requirements.txt
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/bootstrap.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password 
    commands:
      # dynamically select inventory based on Git branch/tag
      - version=$DRONE_BRANCH
      - if [ ! -z $DRONE_TAG ]; then version=production; fi
      - /bin/drone-ansible --inventory .ansible/inventory/$$version/hosts

trigger:
  branch:
    - development
    - stable
  event:
    - push
    - tag

---

kind: pipeline
type: docker
name: daily maintenance


steps:
  - name: update dev
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/update.yaml
      inventory: .ansible/inventory/development
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

  - name: update test
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/update.yaml
      inventory: .ansible/inventory/stable
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

  - name: update prod
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/update.yaml
      inventory: .ansible/inventory/production
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - cron
  cron:
    - daily_maintenance

---

kind: pipeline
type: docker
name: weekly maintenance


steps:
  - name: clean dev
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/clean.yaml
      inventory: .ansible/inventory/development
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

  - name: clean test
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/clean.yaml
      inventory: .ansible/inventory/stable
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

  - name: clean prod
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      PROXMOX_USER:
        from_secret: proxmox_user
      PROXMOX_PASS:
        from_secret: proxmox_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/clean.yaml
      inventory: .ansible/inventory/production
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - cron
  cron:
    - weekly_maintenance
