# ansible-playbook rebuild_certificates.yaml -i inventories/dev/hosts --vault-id ~/.tokens/vault.txt

- hosts: all
  strategy: linear
  gather_facts: yes
  become: yes

  tasks:

    - name: "Rebuild Certificate Bundle on Ubuntu 18"
      shell: /usr/sbin/update-ca-certificates
      become: yes
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '18'
