version: "3.8"

services:
  
  prune_job:
    image: docker
    command: "docker system prune -f"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 */1 * * *" # hourly
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
