# - name: ssh_keyscan
#   scm: git
#   src: "https://github.com/tomdaley92/ansible-role-ssh-keyscan.git"
#   version: "1.0.0"

- name: ubuntu_base
  scm: git
  src: "git@github.com:tomdaley92/ansible-role-ubuntu-base.git"
  version: "stable"

# - name: docker_host
#   scm: git
#   src: "https://github.com/tomdaley92/ansible-role-docker-host.git"
#   version: "1.1.0"
