# ansible-playbook .ansible/deploy.yaml -i .ansible/inventory/development/hosts --vault-id ~/.tokens/master_id

- hosts: all 
  strategy: free
  roles:
    - ubuntu_base

  tasks:
    - include_role:
        name: docker
        tasks_from: install
