collections:

  - name: community.general
  - name: ansible.posix

roles:

- name: ubuntu
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-ubuntu.git"
  version: 3.0.1

- name: docker
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-docker.git"
  version: 2.0.0
