- name: ubuntu
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-ubuntu.git"
  version: 2.1.1

- name: common
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-common.git"
  version: 1.0.0

- name: docker
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-docker.git"
  version: 1.1.0
